stages:
  - images
  - publish

variables:
  DEPS: "/usr/bin/guestfish xz sudo"

.store_images: &store_images
  - xz --verbose *.qcow2
  - mkdir $CI_JOB_NAME
  - mv --verbose *.qcow2.xz $CI_JOB_NAME
  - tree -s -h --charset utf8 -T "$CI_JOB_NAME images" -H "$CI_JOB_URL/artifacts/raw/$CI_JOB_NAME" $CI_JOB_NAME > index.html
  - mv --verbose index.html $CI_JOB_NAME

fedora:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - time dnf install -y $DEPS
  script:
    - time ./Fedora-efi-grub2.sh
    - time ./Fedora-efi-systemd.sh
    - *store_images
  artifacts:
    paths:
      - fedora

centos8:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:centos8
  before_script:
    - time dnf install -y $DEPS
  script:
    - sed -i -e '/proxy/d' repos/centos-8.repo
    - time ./CentOS8-efi.sh
    - *store_images
  artifacts:
    paths:
      - centos8

centos7:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:centos7
  before_script:
    - time yum install -y $DEPS
  script:
    - sed -i -e '/proxy/d' repos/centos-7.repo
    - time ./CentOS7-efi.sh
    - *store_images
  artifacts:
    paths:
      - centos7

pages:
  stage: publish
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  dependencies:
    - fedora
  script:
    - mkdir public
    - mv fedora/index.html public
  artifacts:
    paths:
      - public/

