stages:
  - images
  - publish

fedora:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - time dnf install -y /usr/bin/guestfish /usr/bin/xz
  script:
    - time ./Fedora-efi-grub2.sh
    - xz --verbose *.qcow2
    - tree -s -h -T "fedora images" -I "*.qcow2.xz" -H "$CI_JOB_URL/artifacts/file/" . > index.html
  artifacts:
    paths:
      - fedora-*.qcow2.xz
      - index.html

pages:
  stage: publish
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  dependencies:
    - fedora
  script:
    - mkdir public
    - mv index.html public
  artifacts:
    paths:
      - public/

