stages:
  - images
  - publish

fedora:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - dnf install -y /usr/bin/guestfish /usr/bin/xz
  script:
    - ./Fedora-efi-grub2.sh
    - xz fedora-*.qcow2
  artifacts:
    paths:
      - fedora-*.qcow2.xz

pages:
  stage: publish
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  dependencies:
    - fedora
  script:
    - mkdir public
    - echo "<pre>"      >  index.html
    - set | grep ^CI    >> index.html
    - echo "</pre>"     >> index.html
    - mv index.html public
  artifacts:
    paths:
      - public/

