stages:
  - images
  - publish

image_fedora:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - dnf install -y /usr/bin/guestfish
  script:
    - Fedora-efi-grub2.sh 33
  artifacts:
    paths:
      - Fedora-*.qcow2

pages:
  stage: publish
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  dependencies:
    - image_fedora
  script:
    - mkdir public
    - mv *.qcow2 public
    - tree -T "$CI_PROJECT_NAME rpms" --charset utf8 -H . public > index.html
    - mv index.html public
  artifacts:
    paths:
      - public/

