stages:
  - images
  - publish

.store_images: &store_images
  - xz --verbose *.qcow2
  - mkdir $CI_JOB_NAME
  - mv --verbose *.qcow2.xz $CI_JOB_NAME
  - tree -s -h --charset utf8 -T "$CI_JOB_NAME images" -H "$CI_JOB_URL/artifacts/raw/$CI_JOB_NAME" $CI_JOB_NAME > index.html
  - mv --verbose index.html $CI_JOB_NAME

fedora:
  stage: images
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  before_script:
    - time dnf install -y /usr/bin/guestfish /usr/bin/xz
  script:
    - time ./Fedora-efi-grub2.sh
    - time ./Fedora-efi-systemd.sh
    - *store_images
  artifacts:
    paths:
      - fedora

pages:
  stage: publish
  image: registry.gitlab.com/kraxel/rpm-package-builder:fedora
  dependencies:
    - fedora
  script:
    - mkdir public
    - mv fedora/index.html public
  artifacts:
    paths:
      - public/

